dist: xenial

install:
  - sudo apt-get update && sudo apt-get install -qq wkhtmltopdf php-cli composer php-xml php-mbstring fonts-nanum fonts-nanum-coding fonts-nanum-extra
  - pushd markdown-resume; composer install; popd

script:
  - ./markdown-resume/bin/md2resume html resume.md ./
  - ./markdown-resume/bin/md2resume pdf resume.md ./
  - mv resume.html index.html
  - git clone -b gh-pages --depth=1 https://kjwon15:${GH_TOKEN}@${GH_REF} out
  - mv index.html resume.pdf out/
  - pushd out
  - git add index.html resume.pdf
  - git config user.name "Travis"
  - git config user.email "kjwonmail@gmail.com"
  - git commit -m "Build github pages"
  - git push -f https://kjwon15:${GH_TOKEN}@${GH_REF} gh-pages
